FROM nginx:1.15.8-alpine


copy ./*.html /usr/share/nginx/html/
copy ./styles/*.css /usr/share/nginx/html/styles/
copy ./scripts/*.js /usr/share/nginx/html/scripts/
copy ./images/*.png /usr/share/nginx/html/images/
copy ./images/*.jpg /usr/share/nginx/html/images/


