version: "3.9"

services:
  accounts_db:
    container_name: accounts_db   
    image: postgres:12           
    expose:                        
      - "5433"
    environment:                 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:                      
      - accpgdata:/var/lib/postgresql/data
    command: -p 5433  

  inventory_db:
      container_name: inventory_db   
      image: postgres:12           
      expose:                        
        - "5432"
      environment:                 
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      volumes:                      
        - invpgdata:/var/lib/postgresql/data


  accounts_service:
    container_name: accounts_service
    image: ahmedosamaswe/accounts_service:latest
    build: ./accounts
    environment:
      - DB_URL=postgresql://postgres:postgres@accounts_db:5433/postgres
    depends_on:
      accounts_db:
        condition: service_started

  inventory_service:
    container_name: inventory_service
    image: ahmedosamaswe/inventory_service:latest
    build: ./inventory
    environment:
      - DB_URL=postgresql://postgres:postgres@inventory_db:5432/postgres
    depends_on:
      inventory_db:
        condition: service_started

  api_gateway:
    container_name: api_gateway
    image: nginx
    ports:
      - "8081:8081"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      accounts_service:
        condition: service_started
      inventory_service:
        condition: service_started  

  frontend-server:
    container_name: frontend-server
    image: ahmedosamaswe/frontend-server:latest
    build: ./frontend-server
    ports:
      - "8085:80" 
    depends_on:
      api_gateway:
        condition: service_started

volumes:
  accpgdata: {}
  invpgdata: {}

  